// Import the original config from the @wordpress/scripts package.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugin to remove empty emitted scripts
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );

// Export the webpack config.
module.exports = {
	...defaultConfig,
	entry: {
		...defaultConfig.entry(),
		'button-icon-variation': './src/button-icon-variation/index.js',
		'button-icon-variation-styles': './src/button-icon-variation/style.scss',
	},
	plugins: [
		// Very important! Include WP's plugin config or the
		// world will cease to exist as we know it.
		...defaultConfig.plugins,
		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin( {
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		} ),
	],
};
